//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NIUSBGPIB.RC
//
#define IDC_PB_HELP                     9
#define IDD_NETWORK                     100
#define IDD_DEVICE                      101
#define IDD_DEV_GPIB_STAT               101
#define IDD_DRVF_GET_DRVSTAT            102
#define IDD_DRVF_GET_DEVSTAT            103
#define IDD_DEVF_GET_DEVSTAT            104
#define IDD_DRVF_COMMAND                105
#define IDD_DRVF_PORT_INPUT             106
#define IDD_DRVF_PORT_OUTPUT            107
#define IDD_DRVF_PEEK                   108
#define IDD_DRVF_POKE                   109
#define IDC_CO_DPADR                    200
#define IDC_CO_PORT                     202
#define IDC_CB_SIMULATE                 203
#define IDC_CO_IRQ                      204
#define IDC_CB_CRITICAL                 205
#define IDC_CB_WATCHDOG                 207
#define IDC_RB_HOLDLASTSTATE            208
#define IDC_RB_ZEROOUTPUTS              209
#define IDC_RB_BAUDRATE_125             210
#define IDC_RB_BAUDRATE_250             211
#define IDC_RB_BAUDRATE_500             212
#define IDC_RB_INPUT_READ_COS           214
#define IDC_RB_INPUT_READ_CYCLIC        215
#define IDC_RB_HWTEST_RW                217
#define IDC_RB_HWTEST_OFF               218
#define IDC_CO_ADDRESS                  219
#define IDC_CO_LENGTH                   220
#define IDC_E_COMMAND                   221
#define IDC_E_WBUFFER                   222
#define IDC_E_WLENGTH                   223
#define IDC_E_RBUFFER                   224
#define IDC_E_RLENGTH                   225
#define IDC_E_STATUS                    226
#define IDC_E_ADDRESS                   227
#define IDC_E_RESULT                    228
#define IDC_E_TIMEOUT                   229
#define IDC_E_PCODE                     230
#define IDC_E_EOI                       230
#define IDC_E_VALUE                     231
#define IDC_E_TIMEOUT2                  231
#define IDC_E_STRLEN                    231
#define IDC_E_DDSTATUS                  232
#define IDC_E_VID                       300
#define IDC_E_PID                       301
#define IDC_E_BUSNUM                    302
#define IDC_E_ADDR                      303
#define IDC_E_PORTNUM                   304
#define IDC_E_DEPTH                     305
#define IDC_CO_USB_IDX                  306
#define IDC_COMBO2                      307
#define IDC_CO_USB_CNT                  307
#define IDC_CO_TX_RX                    307
#define IDC_EDIT1                       308
#define IDC_IFNUM                       308
#define IDC_E_IFNUM                     308
#define IDC_COMBO1                      309
#define IDC_CO_GPIB_ADDR                309
#define IDC_CO_BUSNUM                   310
#define IDC_CO_ADDR                     311
#define IDC_E_SND_STRING                311
#define IDC_E_RCV_STRING                312
#define IDC_CO_DEPTH                    313
#define IDC_CB_EOI                      313
#define IDC_CO_BUSNUM2                  314
#define IDC_CO_IFNUM                    314
#define IDC_E_CODE                      315
#define IDD_DEVICE_WRITE                801
#define IDD_DRVF_WRITE                  801
#define IDD_DRVF_READ                   803
#define IDD_DRVF_SET_ADDR               806
#define IDD_DRVF_SET_CODE               808
#define IDD_DRV_CLEAR                   809
#define IDD_DRVF_CLEAR                  809
#define IDS_CP_SOFTWARE_FAULT           1000
#define IDS_CP_TOO_MANY_DRIVERS         1001
#define IDS_CP_DRIVER_NOT_CONFIGURED    1002
#define IDS_CP_DEVICE_NOT_CONFIGURED    1003
#define IDS_CP_UNKNOWN_DEVICE           1004
#define IDS_CP_NO_DEVICES               1005
#define IDS_CP_NETPASS1_ERROR           1006
#define IDS_CP_UNKNOWN_ACCESS           1007
#define IDS_CP_NO_INPUTS                1008
#define IDS_CP_NO_OUTPUTS               1009
#define IDS_CP_NO_MEMORY                1010
#define IDS_CP_NETCONFIG_ID             1011
#define IDS_CP_NETCONFIG_VERS           1012
#define IDS_CP_NETCONFIG_DPADR          1013
#define IDS_CP_NETCONFIG_DPLEN          1014
#define IDS_CP_NETCONFIG_PORT           1015
#define IDS_CP_NETCONFIG_WATCHDOG       1016
#define IDS_CP_NETCONFIG_HWTEST         1017
#define IDS_CP_NETCONFIG_STOPSTATE      1018
#define IDS_CP_NETCONFIG_SIMULATE       1019
#define IDS_CP_NETCONFIG_BAUDRATE       1020
#define IDS_CP_NETCONFIG_IRQ            1021
#define IDS_CP_NETCONFIGSIZE            1022
#define IDS_CP_SAME_DPRADR              1023
#define IDS_CP_SAME_PORT                1024
#define IDS_CP_SAME_IRQ                 1025
#define IDS_CP_DEVCONFIG_NETID          1026
#define IDS_CP_DEVCONFIG_ID             1027
#define IDS_CP_DEVCONFIG_VERS           1028
#define IDS_CP_DEVCONFIG_OFFSET         1029
#define IDS_CP_DEVCONFIG_ADDRESS        1030
#define IDS_CP_DEVCONFIG_SIZE           1031
#define IDS_CP_DEVCONFIG_CRITICAL       1032
#define IDS_CP_DEVCONFIG_FILE           1033
#define IDS_CP_DEVCONFIG_TYPE           1034
#define IDS_CP_DEVCONFIG_ERR            1035
#define IDS_CP_DEVCONFIG_INVALID_PCODE  1036
#define IDS_CP_OVERLAPP                 1040
#define IDS_CP_SAME_DP_ADDRESS          1041
#define IDS_CP_SAME_DEVICE_ADDRESS      1042
#define IDS_CP_DEVCONFIGFIELD           1043
#define IDS_CP_DEVCONFIGSIZE            1050
#define IDS_CP_CANNOT_GET_DEVCONFIG     1051
#define IDS_CP_CANNOT_GET_NETCONFIG     1052
#define IDS_CP_INVALID_PORT             1053
#define IDS_CP_INVALID_DPR              1054
#define IDS_CP_INVALID_STOPSTATE        1055
#define IDS_CP_INVALID_BAUDRATE         1056
#define IDS_CP_INVALID_POINT            1057
#define IDS_CP_POINT_OUTSIDE            1058
#define IDS_CP_INVALID_IRQLEVEL         1059
#define IDS_CP_POINT_OVERLAP            1060
#define IDS_CP_CANNOT_FIND_NETWORK      1061
#define IDS_CP_INVALID_INDEX            1062
#define IDS_CP_INVALID_PCI_COUNT        1063
#define IDS_CP_INVALID_USB_COUNT        1063

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        811
#define _APS_NEXT_COMMAND_VALUE         4000
#define _APS_NEXT_CONTROL_VALUE         316
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
